baseURL = "https://feed.bitsnbeing.com/"
locale = "ru"
title = "My Feed"
theme = "neofeed-theme"

[author]
  name = "Omar"
  image = "/images/avatar.jpg"

[params]
  description = "feed"
  skin = "macintosh"
